import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../components/button'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mood Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{paddingBottom:"20px",position:"relative", height:"400px", width:"300px"}}>
          <Image src="/../public/images/pexels-chevanon-photography-1108099.jpg" alt="Find happiness" layout='fill' objectFit="contain" />
        </div>
        <div>
          <Button value="NEW" link="#" />
        </div>
        <div>
          <Button value="HISTORY" link="#" />
        </div>
      </main>

    </div>
  )
}

export default Home
